# 这是房地产市场洞察项目
1. 导入库
2. 导入数据
3. 数据概览
4. 数据清洗
5. 新数据特征构造
6. 问题分析及可视化

### 1.导入库

In [60]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
from matplotlib import rcParams

rcParams['font.family'] = 'Noto Sans CJK JP'

### 2. 导入数据

In [61]:
df = pd.read_csv('../pandas/data/house_sales.csv')
df.tail()

,city,address,area,floor,name,price,province,rooms,toward,unit,year,origin_url
106113,鹤岗,南山区,73㎡,中层（共6层）,九州新建小区,12万,黑龙江,2室1厅,东西向,1644元/㎡,NaN,https://hegang.esf.fang.com/chushou/16_201235.htm
106114,鹤岗,-鹤岗市兴安区,70㎡,低层（共7层）,滨河南小区,21万,黑龙江,2室1厅,南北向,3000元/㎡,NaN,https://hegang.esf.fang.com/chushou/16_201234.htm
106115,鹤岗,-鹤岗市兴安区,70㎡,低层（共7层）,滨河南小区,21万,黑龙江,2室1厅,南北向,3000元/㎡,NaN,https://hegang.esf.fang.com/chushou/16_201234.htm
106116,鹤岗,工农区,64㎡,高层（共6层）,鹤岗市工农区原消防队三号楼,15万,黑龙江,2室1厅,南北向,2344元/㎡,NaN,https://hegang.esf.fang.com/chushou/16_201236.htm
106117,鹤岗,工农区,64㎡,高层（共6层）,鹤岗市工农区原消防队三号楼,15万,黑龙江,2室1厅,南北向,2344元/㎡,NaN,https://hegang.esf.fang.com/chushou/16_201236.htm

### 3. 数据概览

In [62]:
print('总记录数:', len(df))
print('总字段数量：', len(df.columns))
df.info()

总记录数: 106118
总字段数量： 12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106118 entries, 0 to 106117
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   city        106118 non-null  object
 1   address     104452 non-null  object
 2   area        105324 non-null  object
 3   floor       104024 non-null  object
 4   name        105564 non-null  object
 5   price       105564 non-null  object
 6   province    106118 non-null  object
 7   rooms       104036 non-null  object
 8   toward      105240 non-null  object
 9   unit        105564 non-null  object
 10  year        57736 non-null   object
 11  origin_url  105564 non-null  object
dtypes: object(12)
memory usage: 9.7+ MB

### 4. 数据清洗

### 4.1 缺失值的处理

In [63]:
# 删除无用的数据列
df.drop(columns='origin_url', inplace=True)
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
1,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
3,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37㎡,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建

In [64]:
# 检查是否有缺失值
df.isna().sum()

# 删除缺失值数据
df.dropna(inplace=True)
print('删除后的数据还剩：', len(df))

删除后的数据还剩： 57520

In [65]:
# 检查重复值
df.duplicated().sum()

# 删除重复值
df.drop_duplicates(inplace=True)
print('删除后的数据还剩：', len(df))

删除后的数据还剩： 28104

In [66]:
# 表格中表示房屋面积的都带有单位㎡，删除单位方便后续进行计算
df['area'] = df['area'].str.replace('㎡', '').astype(float)
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46万,安徽,2室1厅,南向,9200元/㎡,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158万,安徽,4室2厅,南向,13167元/㎡,2012年建

In [67]:
# 价格要去掉单位万
df['price'] = df['price'].str.replace('万', '').astype(float)
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649元/㎡,2017年建
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200元/㎡,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167元/㎡,2012年建

In [68]:
# 房屋朝向类型转换
df['toward'] = df['toward'].astype('category')

In [69]:
# 每平米的价格去掉元/㎡
df['unit'] = df['unit'].str.replace('元/㎡', '').astype(float)
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017年建
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012年建

In [70]:
# 建造年份需要处理
df['year'] = df['year'].str.replace('年建', '').astype(int)
df.head()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012

### 4.2 异常值的处理

In [71]:
# 面积的异常
print('面积太小房屋：\n', df[df['area'] < 20])
print('面积太大的房屋：\n', df[df['area'] > 600])

df = df[(df['area'] > 20) & (df['area'] < 600)]

面积太小房屋：
        city                address   area     floor     name  price province  \
102      合肥         新省府-包河大道与南京路交口  11.00  中层（共27层）   招商·雍华府   22.0       安徽
980      天津         体育馆街-成都道与桂林路交口  11.86   高层（共1层）    成都道小区  140.0      直辖市
6366     杭州  北干-天汇园星云地带新区金城路金鸡路交叉处  17.00  中层（共28层）  天汇园星云地带   50.0       浙江
8388     丽水  北郭桥/白云-莲都-北郭桥/白云-汽运宿舍  17.00   高层（共1层）     汽运宿舍   48.0       浙江
28798    毕节         黔西县-黔西南部新区教育园区  11.00  低层（共31层）    黔西阳光城   42.0       贵州
40546    巢湖         新省府-包河大道与南京路交口  11.00  中层（共27层）   招商·雍华府   22.0       安徽
40886    蚌埠               张公山-红旗一路  15.00   低层（共7层）   朝阳新村三村   24.5       安徽
40892    蚌埠          淮河路-胜利东路1556号  10.00  中层（共11层）     百合公馆  132.0       安徽
50780    泸州       蓝田-江阳区-蓝田-江阳区-蓝田  18.00   中层（共2层）   江阳区-蓝田   35.0       四川
68686    开阳             小十字-飞山街42号  14.00  低层（共23层）    飞山街小区   13.0       贵州
80478    孝感    中心城区-孝南-中心城区-润达壹号广场  10.00  低层（共16层）   润达壹号广场   14.0       湖北
94170    清镇          紫林庵-飞山街中医二附院旁  12.47  低层（共23层）  飞山街电信宿舍   12.4       贵州
94178    清镇             小十字-飞山街42号  14.00  低层（共23层）    飞山街小区   13.0       贵州
98540    咸宁         沃尔玛购物广场-温泉路37号  18.00   低层（共5层）     光谷广场   32.0       湖北
100038   咸宁         沃尔玛购物广场-温泉路37号  12.00   低层（共5层）     光谷广场   25.0       湖北

       rooms toward      unit  year
102     2室1厅     南向   20000.0  2018
980     1室0厅     东向  118044.0  1998
6366    2室2厅     南向   29412.0  2016
8388    1室1厅    南北向   28235.0  1990
28798   3室2厅    南北向   38182.0  2019
40546   2室1厅     南向   20000.0  2018
40886   1室0厅     南向   16333.0  2000
40892   3室2厅    南北向  132000.0  2010
50780   1室1厅     南向   19444.0  2015
68686   1室1厅    东南向    9286.0  1998
80478   1室1厅    南北向   14000.0  2019
94170   1室1厅     东向    9944.0  2000
94178   1室1厅    东南向    9286.0  1998
98540   1室1厅    南北向   17778.0  2018
100038  1室1厅     南向   20833.0  2018
面积太大的房屋：
        city                   address    area     floor      name  price  \
4710     贵阳  高新区-金苏大道绿地新都会(金融中心前行5公里)   752.0  低层（共23层）     绿地新都会  500.0
5854     衡水     衡百国际-胜利路与宝云街交叉口德隆超市对面   990.0  中层（共24层）       橄榄城   77.0
6834     邯郸                丛台-油漆厂路16号  2019.0  中层（共30层）    恒大翡翠御庭  113.0
44240    桂林              八里街-八里六路城北菜市  1675.0   低层（共7层）      城北小区  360.0
68248    耒阳                立新开发区-红湘北路  1401.0  中层（共28层）      香格里拉   71.0
74440    梅州            梅江-广东梅州江南梅水路附近   700.0   低层（共7层）     梅水路附近  468.0
103504   舟山          舟山中学-翡翠道路与桃湾路交叉口  2020.0   中层（共6层）  光明·东方大境府  240.0

       province rooms toward    unit  year
4710         贵州  1室1厅     南向  6649.0  2018
5854         河北  2室2厅     南向   778.0  2010
6834         河北  3室2厅    南北向   560.0  2019
44240        广西  9室9厅     南向  2149.0  2018
68248        湖南  3室2厅    南北向   507.0  2013
74440        广东  9室9厅    东南向  6686.0  2005
103504       浙江  4室2厅    南北向  1188.0  2019

In [72]:
# 房屋售价的异常处理
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df['price'] > lower_bound) & (df['price'] < upper_bound)]

### 5. 新数据特征构造
- 构造新的列

In [75]:
# 区名district
df['district'] = df['address'].str.split('-').str[0]  # 取 split 之后列表里的第一个元素
df.sample(5)

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district
70828,龙口,度假区-东海旅游度假区,74.00,中层（共17层）,金域蓝湾B区,42.3,山东,2室2厅,南北向,5716.0,2016,度假区
16656,湛江,赤坎-军民路43号(金沙湾小区北侧),81.00,高层（共31层）,城市汇峰,78.0,广东,3室2厅,东南向,9630.0,2016,赤坎
94790,南充,嘉陵新区-充市嘉陵区春江路二段与迎宾路交界,97.00,中层（共33层）,金科集美嘉悦,52.0,四川,3室2厅,南向,5361.0,2019,嘉陵新区
34268,泰安,泰安东区-东岳大街与天烛峰路交汇处西200米路南,129.00,高层（共20层）,拉菲公馆,140.0,山东,3室2厅,南向,10853.0,2015,泰安东区
38332,石家庄,天山海世界-珠峰大街218号(珠峰大街与珠江大道交口西北,87.19,低层（共32层）,水榭花都,134.0,河北,3室2厅,南北向,15369.0,2010,天山海世界

In [79]:
# 楼层类型floor_type
def fun1(str1):
    if pd.isna(str1):
        return '未知'
    elif '低' in str1:
        return '低楼层'
    elif '中' in str1:
        return '中楼层'
    elif '高' in str1:
        return '高楼层'
    else:
        return '未知'


df['floor_type'] = df['floor'].apply(fun1).astype('category')
df.sample(5)

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district,floor_type
68282,耒阳,立新开发区-蒸湘区立新大道,138.0,中层（共30层）,水映豪廷,108.0,湖南,3室2厅,南北向,7826.0,2015,立新开发区,中楼层
33376,如皋,如皋市区-如皋-如皋市区-金润玺景苑(别墅),270.0,高层（共1层）,金润玺景苑(别墅),290.0,江苏,5室3厅,南向,10741.0,2017,如皋市区,高楼层
58110,偃师,火车站-华山北路与汉宫路交会处,89.0,低层（共32层）,和昌·云庭,72.0,河南,3室2厅,南向,8090.0,2016,火车站,低楼层
12688,太仓,新区-北京东路,91.0,低层（共11层）,恒通佳苑,78.0,江苏,3室2厅,南向,8571.0,2011,新区,低楼层
11132,太仓,沙溪-印溪南路北、镇东路以西,113.6,高层（共1层）,诺丁公馆,110.0,江苏,4室2厅,南向,9683.0,2017,沙溪,高楼层

In [56]:


# 是否为直辖市 is_municipality
# 卧室数量 bedrooms
# 客厅数量 livingrooms
# 楼龄 building_age
# 价格分段 price_labels

0            龙岗
2          生态公园
4            撮镇
6            龙岗
8         新亚汽车站
          ...
106080     万达广场
106082     万达广场
106084     万达广场
106086     利州广场
106088     永隆百货
Name: address, Length: 25382, dtype: object

### 6. 问题分析及可视化